exports.getGombal = () => {
        let gombalan = [
                "ibaratkanlah kehilangan cinta itu seperti hilangnya cincin permata di lautan luas yang tiada bertepi dan harus dilupakan",
                "Aku rela jadi abang nasi goreng asalkan setiap malam aku bisa lewat depan rumah kamu",
                "Kalo nanti malam ada Pocong ngintip di jendela, jangan takut yah, Dia memang sengaja aku suruh untuk jagain kamu bobo",
                "Air mata yang tak terbendung bukanlah lambang kelemahan, terkadang Ia hadir untuk memurnikan masa lalu menuju kehidupan baru",
                "Aku rela dipenjara seumur hidup asalkan pelanggarannya karena mencintaimu",
                "Gimana aku bisa lupa sama kamu, setiap aku memejamkan mata, hanya ada senyuman kamu yang terlihat",
                "Kalo naik motor sama kamu pasti ditilang deh. Soalnya kita kan berTiga, Aku, Kamu, dan Cinta.",
                "Ke Bekasi beli sarapan, Sarapan bubur dapetnya susu. Terimakasih telah memberi harapan, Walau hanya harapan palsu",
                "Neng, bakar-bakaran yuk | Bakar apa? | Kita bakar masa lalu dan buka lembaran baru dengan cinta kita.",
                "Di atas langit masih ada langit ! Di bawah langit masih ada aku yang tulus mencintaimu",
                "Mbak, aku pesen nasi goreng 1 sama Jus 1 yah | Jus apa mas? | Jus the way you are",
                "Orangtuamu pengrajin bantal yah? Karena terasa nyaman jika di dekatmu.",
                "Sekarang aku gendutan gak sih ? kamu tau gak kenapa ? soalnya km udah mengembangkan cinta yang banyak dihatiku",
                "Tau ga knapa malem ini ga ada bintang ?? soalnya bintangnya pindah semua ke matamu?",
                "Jangan GR deh. Aku kangen kamu sedikit aja kok. Sedikit berlebihan maksudnya.",
                "Cuma ada tiga macam cinta yang tak akan pernah berakhir: cinta ibu pd anaknya,cinta fitri dan cintaku padamu.",
                "Mungkin Tuhan sudah hafal do’aku. soalnya monoton. selalu ada tentang kamu.",
                "Aku ga lulus Ulangan Umum sayang, gara2 di bagian essay nya aku tulis surat cinta buat kamu.",
                "KERA apa yang harus dimusnahkan? KERAguan untuk melamarmu.",
                "SETAN apa yg bikin aku bahagia? SETANkai mawar merah darimu",
				"Maksud hati memeluk gunung, apalah daya aku lebuh suka memeluk kamu.",
				"Kamu tu kayak warteg, sederhana namun berkualitas.",
				"Aku gak sedih kok kalo besok hari senin, aku sedihnya kalau gak ketemu kamu",
				"Biarpun kamu gendut, tapi kamu tetep muat kok masuk di hatiku.",
				"Cintaku kepadamu itu bagaikan metabolisme, yang gak akan berhenti sampai mati.",
				"Cukup harga bensin saja yang turun, perasaanmu jangan.",
				"Kamu tau gak apa persamaannya kamu sama AC? Sama-sama bikin aku sejuk.",
				"Aku gak akan ngiler kalau hanya karena harta, tahta, dan wanita. Aku hanya ngiler… saat tidur miring.",
				"Jika aku jadi wakil rakyat sepertinya kau bakal gagal deh? Gimana aku mikirin rakyat, kalau yang ada dipikiranku hanyalah KAMU.",
				"Aku hanya ingin hidup cukup. Cukup lihat senyummu setiap hari.",
				"Cita-citaku dulu pengen jadi dokter tapi setelah mengenalmu, berubah jadi ingin membahagiakanmu.",
				"Mungkin aku ditakdirkan buta, buta untuk melihat wanita lain selain dirimu, I love You.",
				"Aku rela ikut lomba lari keliling dunia, asalkan engkau yang menjadi garis finishnya.",
				"Kopi apa yang paling manis? Kopi-nang kau dengan bismillah.",
				"Bahu jalan untuk darurat, Bahu aku untuk kamu.",
				"Selain ada garuda di dadaku, di dadaku juga selalu ada kamu.",
				"Meskipun kamu kurus, kamu adalah hal terberat yang ada di hatiku.",
                "Tau ga kenapa aku mau masuk elektro? aku mau bikin Pembangkit Listrik Tenaga Cinta. Pasti rumah kita paling terang",
                "Kalo kamu lagi di AS, Patung Liberty ga akan bawa obor tapi bakal bawa BUNGA!",
                "kamu juara lomba layangan nasional ya? Pantes paling pinter narik ulur perasaanku",
                "Tahu gak kenapa kita cuma bisa lihat pelangi setengah lingkaran? Sebab setengahnya lagi ada di mata kamu.",
                "Seperti rakyat di Ethiopia sana yang sedang kelaparan. Sama seperti mereka, aku juga kelapan, ya kelaparan akan cinta darimu.",
                "Teh manisnya tidak perlu pakai gula ya. Kalau pengen manis cukup liat kamu saja.",
                "Pepatah mengatakan, Empat sehat lima sempurna. Namun, aku tidak merasakan kesempurnaan itu sebelum aku merasakan kasih sayangmu.",
                "Kamu lebih istimewa dari Komet Halley yg muncul 76 tahun sekali. Karena kamu muncul satu kali dalam hidupku dan tak tergantikan.",
                "Eh pinjem flashdisk dong, aku pengen transfer data cintaku buat kamu.",
                "Aku sekarang berada di pos keamanan Dufan gara-gara berantem sama penjaga loket. Aku bilang mau tiket terusan ke hati kamu tapi tidak ada.",
                "Makna dari rumus e = m . c^2  yaitu [engkau = manis . cantiknya emang kodrat mu]",
                "Boleh dong minta foto kamu? Aku mau nunjukin temenku kalau bidadari itu beneran ada.",
                "Mungkin aku kiper terburuk sedunia, membiarkan kamu membobol gawang berkali-kali dengan cintamu.",
                "Sejak kapan kamu jadi penari? Terus kenapa bayanganmu selalu menari-nari dibenakku.",
                "Cuma tiga cinta yang tdk akan pernah berakhir: cinta ibu pd anaknya,cinta fitri dan cintaku padamu.",
                "Di rumah sakit banyak tabung oksigen, tapi waktu aku sesek napas, aku bilang sama susternya, aku cuma butuh kamu. soalnya kamu oksigen aku.",
                "Cintaku padamu bagaikan ban kereta api yang tidak bisa kempes.",
                "Kalau kamu adalah Bumi, maka aku adalah atmosfirnya. Dengan begitu setiap saat bisa melindungimu dari sakitnya serangan meteor dan komet.",
                "Apabila kamu matahari, maka aku jadi bulan. Yang memantulkan cahayamu agar bumi tidak gelap setelah kau pergi.",
                "Kalau kamu adalah pedagang pasar. Maka aku adalah premannya yang memberimu rasa aman.",
                "kak, katanya kalau mau sukses harus bangun subuh ya? Itu orang sukses apa orang bekasi",
                "Orang bilang cinta itu dikejar, jadi enggak usah heran kalau sampai sekarang aku masih ngejar kamu",
                "Saya di tilang karena apa pak? Kurang manis kalau pakai HELM",
                "Ngeliat kamu tuh seperti lihat kamera, bawaanya pengen senyum terus",
                "Daripada debat sama cewek mending nguras sumur pakai gelas, capeknya sama",
                "Tunda lapar, makan indomie hati menggelapar cintapun bersemi",
                "Jangankan ice cream, neng minta hati abang pasti kasih",
                "Daripada jadi pemimpin negara, mendingan menjadi pemimpin hati kamu",
                "Di mobil kamu ada yang wangi, kalau di mata kamu ada pelangi",
				"Sejak mengenalmu bawaannya aku pengen belajar terus, Belajar menjadi yang terbaik buat kamu.",
				"Bagaimana kalau kita berdua jadi komplotan perampok?. Aku merampok hatimu dan kamu merampas hatiku.",
				"Kamu tau gak? Kenapa kalau aku menghafal lihatnya ke atas?, soalnya kalau merem langsung kebanyang wajahmu.",
				"Orang kurus itu setia, makan aja tidak pernah nambah apalagi pasangan.",
                "Kabinet Jokowi-Jk aja sudah dipilih, Eneng kapan Abang pilih buat jadi istri",
        ];

        let random = Math.floor(Math.random() * (gombalan.length - 0) + 0);

        return gombalan[random];
}